name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.eddbc9ea-8fa7-446f-9b67-ccfd0a71b299 }}
          GH_TOKEN: ${{ secrets.0dd54f90a72c51e95acc581b72394bb804de6a88}}      
          SHOW_LINES_OF_CODE: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LOC_CHART: "True"
          SHOW_PROFILE_VIEWS: "True"        
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"  