name: Waka Readme Stats
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Atualiza todos os dias à meia-noite (UTC)
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
